version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  server:
    build: server/
    command: python ./server.py
    ports:
      - 8080:8080
