version: "3"

services:
  postgres:
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth_test

  server:
    build: /
    command: python ./server.py
    ports:
      - 8080:8080
