version: "3"

services:
  postgres:
    image: postgres:11.3-alpine
    env_file:
      - .env
    ports:
      - "${LOCAL_PORT}:${IMAGE_PORT}"

  server:
    env_file:
      - .env
    volumes:
      - ./:/var/www/
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
